apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperfleet-nodepool-vr-adapter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: '{{ .Values.git_repo }}'
    targetRevision: '{{ .Values.git_revision }}'
    path: helm/charts/hyperfleet-nodepool-vr-adapter
    helm:
      valuesObject:
        projectId: '{{ .Values.project_id }}'
        region: '{{ .Values.region }}'
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: 'nodepool-vr-adapter@{{ .Values.project_id }}.iam.gserviceaccount.com'
        pubsub:
          subscription: hyperfleet-nodepool-events-nodepool-vr-adapter
  destination:
    server: https://kubernetes.default.svc
    namespace: hyperfleet
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
