apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maestro-server-cloud-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/openshift-online/maestro
    targetRevision: v0.5.0
    path: charts/maestro-server-cloud-resources
    helm:
      valuesObject:
        gcp:
          projectId: '{{ .Values.project_id }}'
          region: '{{ .Values.region }}'
        database:
          enabled: true
        pubsub:
          enabled: true
          topics:
            - sourceEvents
            - sourceBroadcast
            - agentEvents
            - agentBroadcast
  destination:
    server: https://kubernetes.default.svc
    namespace: maestro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
