apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: gcp-hcp-demo
  namespace: promoter-system
spec:
  gitRepositoryRef:
    name: gcp-hcp-gitops-promoter-demo
  activeCommitStatuses:
    - key: ci-check
    - key: deploy
  environments:
    - branch: environment/integration/main
    - branch: environment/stage/main
      activeCommitStatuses:
        - key: timer
    - branch: environment/production/prod-1
      autoMerge: false
    - branch: environment/production/prod-2
    - branch: environment/production/prod-3
