apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  name: github
  namespace: promoter-system
spec:
  secretRef:
    name: github-app-key
  github:
    appID: 0
    installationID: 0
